### 1. Регистрация обычного пользователя
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "artem",
  "password": "wirderledigt"
}

### 2. Логин пользователя (получение токенов)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "artem",
  "password": "wirderledigt"
}

> {%
    client.global.set("user_access_token", response.body.accessToken);
    client.global.set("user_refresh_token", response.body.refreshToken);
%}

### 3. Информация о текущем пользователе
GET http://localhost:8080/auth/me
Authorization: Bearer {{user_access_token}}

### 4. Создание задачи
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer {{user_access_token}}

{
  "title": "Сделать лабораторную",
  "status": "OPEN"
}

> {% client.global.set("last_task_id", response.body.id); %}

### 5. Попытка удаления задачи обычным пользователем (ожидается 403)
DELETE http://localhost:8080/tasks/{{last_task_id}}
Authorization: Bearer {{user_access_token}}

### 6. Логин администратора
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "neuigkeit123"
}

> {% client.global.set("admin_access_token", response.body.accessToken); %}

### 7. Удаление задачи администратором (ожидается 204)
DELETE http://localhost:8080/tasks/{{last_task_id}}
Authorization: Bearer {{admin_access_token}}

### 8. Обновление токена
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{user_refresh_token}}"
}

### 9. Неверный формат токена (ожидается 401)
GET http://localhost:8080/auth/me
Authorization: Bearer thisisnottokenatall

### 10. Неверная подпись (ожидается 401)
GET http://localhost:8080/auth/me
Authorization: Bearer eyJyb2xlcyI6WyJVU0VSIl0sImV4cCI6MTc3MzI2NDUwOSwidXNlcklkIjoyLCJpYXQiOjE3NzMyNjM2MDksInVzZXJuYW1lIjoiYXVmZ2FiZSJ9.fakesignature

### 11. Истёкший токен (ожидается 401)
GET http://localhost:8080/auth/me
Authorization: Bearer eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdCIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjE3MDAwMDA5MDB9.fakesignature

### 12. Отсутствует заголовок Authorization (ожидается 401)
GET http://localhost:8080/auth/me